name: gcp-infrastructure
runtime: python
description: GCP infrastructure for multi-cloud API deployment

config:
  deploymentType:
    type: string
    default: functions
  appName:
    type: string
    default: multi-cloud-api
  gcpProject:
    type: string
  region:
    type: string
    default: us-central1
  zone:
    type: string
    default: us-central1-a
